'''
Generate the lookup table from ``iconv --list``
'''

__version__ = '0.0.1'

from pprint import pprint as pp

def call_iconv_list():
    import sys
    import subprocess
    try:
        res = subprocess.check_output(['iconv', '--list'])
        res = res.decode()
    except FileNotFoundError:
        sys.stderr.write('iconv not available\n')
    except subprocess.CalledProcessError:
        sys.stderr.write('Error happened when calling iconv\n')
    else:
        return [s.strip('/') for s in res.split()]

def dump_vim_dict(ilist, out):
    out.write('" Generated by genlookup.py (version %s); Do not edit.\n\n' % __version__)
    out.write('let tokenize#lookup#Table = {\n')
    for name in ilist:
        out.write('  \\ %r: 1,\n' % name)
    out.write('  \\}\n')

def main():
    import argparse
    parser = argparse.ArgumentParser(description='Generate lookup table from iconv --list')
    parser.add_argument('out', type=argparse.FileType('w'), help='output file path')
    args = parser.parse_args()
    ilist = call_iconv_list()
    with args.out as out:
        return dump_vim_dict(ilist, out)


if __name__ == '__main__':
    main()
