'''
Generate a vader file to test tokenize().
'''

import os
__version__ = '0.0.2'

TEMPLATE = '''
Assert tokenize#test#against({filename!r})
'''

def glob_pyfiles(dir):
    for dirpath,_,filenames in os.walk(dir):
        for filename in filenames:
            if filename.endswith('py'):
                yield os.path.join(dirpath, filename)

def make(dir, output, fast):
    with output as f:
        f.write('" Generated by genvader.py (%s). Do not edit!\n\n' % __version__)
        if fast:
            f.write('Execute(TokenizeTest);\n')
        for count, filename in enumerate(glob_pyfiles(dir)):
            if not fast:
                f.write('Execute(#%04d);\n' % count)
            f.write(TEMPLATE.format(filename=filename))

def main():
    import argparse
    import sys

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-V', '--version', action='version',
            version='%(prog)s {version}'.format(version=__version__))
    parser.add_argument('dir', type=str,
            help='Directory to look for python files')
    parser.add_argument('-o', '--output', dest='output', default=sys.stdout,
            type=argparse.FileType('w'), help='Output file')
    parser.add_argument('-f', '--fast', dest='fast', action='store_true', default=False,
            help='Fast version, all Asserts in one Execute() block')

    args = parser.parse_args()
    return make(os.path.abspath(args.dir), args.output, args.fast)

if __name__ == '__main__':
    main()
